"""added the order_price in order table

Revision ID: 9a57e959269b
Revises: e08bb30a9b16
Create Date: 2026-06-26 13:44:48.749914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a57e959269b'
down_revision: Union[str, Sequence[str], None] = 'e08bb30a9b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_price')
    # ### end Alembic commands ###
