"""added the product naem in order table

Revision ID: e08bb30a9b16
Revises: dc8eb76e2d21
Create Date: 2026-06-26 12:47:41.071532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08bb30a9b16'
down_revision: Union[str, Sequence[str], None] = 'dc8eb76e2d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('product_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'product_name')
    # ### end Alembic commands ###
