"""for got to add user created at time

Revision ID: f27a4628d4f1
Revises: 48d1db7c86e2
Create Date: 2026-06-25 23:09:54.939919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27a4628d4f1'
down_revision: Union[str, Sequence[str], None] = '48d1db7c86e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('product', 'warehouse_pin', new_column_name='warehouse_pincode')
    op.add_column('user', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.alter_column('product', 'warehouse_pincode', new_column_name='warehouse_pin')
   
    # ### end Alembic commands ###
