"""v1 of user table

Revision ID: f4c4048f83fe
Revises: e1ff59ebc4ba
Create Date: 2026-06-25 01:50:08.625364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c4048f83fe'
down_revision: Union[str, Sequence[str], None] = 'e1ff59ebc4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('inventory', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('product_type', sa.String(), nullable=False))
    op.add_column('user', sa.Column('discount_status', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user', sa.Column('discount_percent', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user', sa.Column('warehouse_pin', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'warehouse_pin')
    op.drop_column('user', 'discount_percent')
    op.drop_column('user', 'discount_status')
    op.drop_column('user', 'product_type')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'inventory')
    op.drop_column('user', 'product_name')
    # ### end Alembic commands ###
